# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22d9ec5adcab64863bd2ce95a3c7c9fb71dc1352dbde9c87e9414a2ad6e8504f6fbebf7979358d9b0b5e67298c29d91c526803a1f2f8bc317ef1447fe91b62ed

test:
  secret_key_base: 6e5b3c8837f7859b77de6d5b60c391efb1c677bbfc9aadf54ca59c5264e855c45bbc5a9f1b145ea76626b3dbf304b8fcb8a3c035920ba635df9da14aca18e8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
